name: NODE CI

on:
  - push
  - pull_request
  
    
jobs:
  build:

    runs-on: ubuntu-latest
    

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          make setup
        env:
          CI: true
          SESSION_KEY: ${{ secrets.SESSION_KEY }}
      - name: Run linter
        run: |
          make lint
      - name: test
        run: |
          make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true